Adds support for detaching kernel drivers.
LibUsbDotNet/LibUsbDotNet pull request #165
Opened 2022-07-04 16:13 UTC by JoeGilkey

This adds support for the attach/detach of kernel drivers.

2022-10-14 06:38 UTC, GreenShadeZhang commented
Has anyone dealt with this issue?

2022-10-16 05:13 UTC, mcuee commented
@GreenShadeZhang 

So you have tested this pull request and it is okay?

2022-10-16 05:15 UTC, mcuee commented
When it comes to codes, we need @qmfrederik to review. Sorry but I know very little of dotnet myself.

2022-10-16 05:22 UTC, mcuee commented
Not so sure why one of the github action failed. It does not seem to be caused by the pull request.

2022-10-28 21:42 UTC, qmfrederik commented
This looks good to me at first glance, did anyone manage to test this?

2022-10-28 23:29 UTC, mcuee commented
@GreenShadeZhang

Have you tested this pull request? Please share your test results. Thanks.

2022-10-29 01:03 UTC, GreenShadeZhang commented
> @GreenShadeZhang
> 
> Have you tested this pull request? Please share your test results. Thanks.

I only tested the two methods I used in the v2 branch, and I didn't test the PR of this main branch.
https://github.com/LibUsbDotNet/LibUsbDotNet/pull/172

2023-02-07 11:53 UTC, mcuee commented
@JoeGilkey 

Can you post some test results for this PR? Thanks.

2023-04-08 14:01 UTC, mcuee commented
@JoeGilkey and @GreenShadeZhang

Just wondering if you can provide a simple sample program so that I can test it under Linux/macOS/Windows? If the test results are positive, I think I can merge the PR.

2023-04-09 05:36 UTC, mcuee commented
@sdijoseph 

Sorry but just wondering if you can provide a simple example to test this. It seems to be safe to merge but still good to have a simple example to carry out the tests.

2023-04-09 06:38 UTC, mcuee commented
BTW, there is a github action build failure for libusbdotnet_windows. Strange. On my local Windows machines I do not see issues.

```
PS C:\work\libusb\libusbdotnet\libusbdotnet_pr165> dotnet test .\src\LibUsbDotNet.Tests\LibUsbDotNet.Tests.csproj
  Determining projects to restore...
  All projects are up-to-date for restore.
  LibUsbDotNet -> C:\work\libusb\libusbdotnet\libusbdotnet_pr165\src\LibUsbDotNet\bin\Debug\netcoreapp3.1\LibUsbDotNet.
  dll
  LibUsbDotNet.Tests -> C:\work\libusb\libusbdotnet\libusbdotnet_pr165\src\LibUsbDotNet.Tests\bin\Debug\net6.0\LibUsbDo
  tNet.Tests.dll
Test run for C:\work\libusb\libusbdotnet\libusbdotnet_pr165\src\LibUsbDotNet.Tests\bin\Debug\net6.0\LibUsbDotNet.Tests.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.4.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     4, Skipped:     0, Total:     4, Duration: 5 ms - LibUsbDotNet.Tests.dll (net6.0)
```

2023-04-10 04:37 UTC, sdijoseph requested changes
These are my suggested changes, mainly just:
- Add XML comments.
- Fix return value of SupportsDetachKernelDriver.
- Throw on errors instead of just returning a bool on most methods.

2023-04-10 04:37 UTC, sdijoseph commented on src/LibUsbDotNet/LibUsb/UsbDevice.KernelDriver.cs
> +using System.Collections.ObjectModel;
```suggestion
```
Unneeded using directives.

2023-04-10 04:37 UTC, sdijoseph commented on src/LibUsbDotNet/LibUsb/UsbDevice.KernelDriver.cs
> +        }
```suggestion
        /// <summary>
        /// Determine if this platform supports detaching the kernel driver.
        /// </summary>
        /// <returns>True if kernel driver detach supported, false otherwise.</returns>
        public bool SupportsDetachKernelDriver() => 
            NativeMethods.HasCapability((uint)Capability.SupportsDetachKernelDriver) != 0;
```
Should report success on non-zero values.

2023-04-10 04:37 UTC, sdijoseph commented on src/LibUsbDotNet/LibUsb/UsbDevice.KernelDriver.cs
> +         }
```suggestion

        /// <summary>
        /// Determine if a kernel driver is active on an interface.
        /// </summary>
        /// <remarks>
        /// If a kernel driver is active, you cannot claim the interface, and libusb will be unable to perform I/O.
        /// This functionality is not available on Windows.
        /// </remarks>
        /// <param name="interfaceNumber">The interface to check.</param>
        /// <returns>True if kernel driver active, false otherwise.</returns>
        public bool IsKernelDriverActive(int interfaceNumber)
        {
            EnsureOpen();
            return NativeMethods.KernelDriverActive(DeviceHandle, interfaceNumber).GetValueOrThrow() == 1;
        }
```

Use GetValueOrThrow since this native method can return multiple errors. 
Return type of NativeMethods.KernelDriverActive needs to be changed to Error from int, not sure if it's possible to suggest that directly.

2023-04-10 04:37 UTC, sdijoseph commented on src/LibUsbDotNet/LibUsb/UsbDevice.KernelDriver.cs
> +        }
```suggestion
        /// <summary>
        /// Detach a kernel driver from an interface.
        /// </summary>
        /// <remarks>
        /// If successful, you will then be able to claim the interface and perform I/O.
        /// This functionality is not available on Windows.
        /// Note that libusb itself also talks to the device through a special kernel driver,
        /// if this driver is already attached to the device, this call will not detach it and throw a
        /// <see cref="Error.NotFound"/> <see cref="UsbException"/>
        /// </remarks>
        /// <param name="interfaceNumber">The interface to detach the driver from.</param>
        public void DetachKernelDriver(int interfaceNumber)
        {
            EnsureOpen();
            NativeMethods.DetachKernelDriver(DeviceHandle, interfaceNumber).ThrowOnError();
        }
```
ThrowOnError instead of returning a bool.

2023-04-10 04:37 UTC, sdijoseph commented on src/LibUsbDotNet/LibUsb/UsbDevice.KernelDriver.cs
> +        }
```suggestion
        /// <summary>
        /// Re-attach an interface's kernel driver, which was previously detached using <see cref="DetachKernelDriver"/>.
        /// </summary>
        /// <remarks>This functionality is not available on Windows.</remarks>
        /// <param name="interfaceNumber">The interface to attach the driver from.</param>
        public void AttachKernelDriver(int interfaceNumber)
        {
            EnsureOpen();
            NativeMethods.AttachKernelDriver(DeviceHandle, interfaceNumber).ThrowOnError();
        }
```
Same as above.

2023-04-10 04:37 UTC, sdijoseph commented on src/LibUsbDotNet/LibUsb/UsbDevice.KernelDriver.cs
> +        }
```suggestion
        /// <summary>
        /// Enable/disable libusb's automatic kernel driver detachment.
        /// </summary>
        /// <remarks>
        /// When this is enabled libusb will automatically detach the kernel driver on an interface when claiming the
        /// interface, and attach it when releasing the interface.
        /// Automatic kernel driver detachment is disabled on newly opened device handles by default.
        /// </remarks>
        /// <param name="autoDetach">Whether to enable or disable auto kernel driver detachment.</param>
        /// <returns>True if the current platform supports kernel driver detachment, false otherwise.</returns>
        public bool SetAutoDetachKernelDriver(bool autoDetach)
        {
            EnsureOpen();
            return NativeMethods.SetAutoDetachKernelDriver(DeviceHandle, autoDetach ? 1 : 0) == Error.Success;
        }
```
Just add XML comment.

2023-04-10 04:41 UTC, sdijoseph commented
> @sdijoseph
> 
> Sorry but just wondering if you can provide a simple example to test this. It seems to be safe to merge but still good to have a simple example to carry out the tests.

With my above suggested changes, I tested this out on my keyboard, as it was one of the few devices that had an active kernel driver:

```
using LibUsbDotNet;
using LibUsbDotNet.LibUsb;

using var context = new UsbContext();
// context.SetDebugLevel(LogLevel.Debug);
using var devices = context.List();
using var device = devices.FirstOrDefault(dev => dev.VendorId == 0x04f3 && dev.ProductId == 0x2014) as UsbDevice;
if (device is null)
{
    Console.WriteLine("Can't find device.");
    return;
}

device.Open();
Console.WriteLine($"Device VID: {device.VendorId:X4} PID: {device.ProductId:X4}");
Console.WriteLine($"Does this device support kernel driver attach: {device.SupportsDetachKernelDriver()}");
Console.WriteLine("Activate auto detach kernel driver.");
device.SetAutoDetachKernelDriver(true);
Console.WriteLine($"Is kernel driver attached to interface: {device.IsKernelDriverActive(0)}");
device.ClaimInterface(0);
Console.WriteLine("Claimed interface");
Console.WriteLine($"Is kernel driver attached to interface: {device.IsKernelDriverActive(0)}");
device.ReleaseInterface(0);
Console.WriteLine("Released interface");
Console.WriteLine($"Is kernel driver attached to interface: {device.IsKernelDriverActive(0)}");
Console.WriteLine("Deactivate auto detach kernel driver.");
device.SetAutoDetachKernelDriver(false);
Console.WriteLine("Detaching kernel driver from interface.");
device.DetachKernelDriver(0);
Console.WriteLine($"Is kernel driver attached to interface: {device.IsKernelDriverActive(0)}");
Console.WriteLine("Attaching kernel driver from interface");
device.AttachKernelDriver(0);
Console.WriteLine($"Is kernel driver attached to interface: {device.IsKernelDriverActive(0)}");
```

```
Device VID: 04F3 PID: 2014
Does this device support kernel driver attach: True
Activate auto detach kernel driver.
Is kernel driver attached to interface: True
Claimed interface
Is kernel driver attached to interface: False
Released interface
Is kernel driver attached to interface: True
Deactivate auto detach kernel driver.
Detaching kernel driver from interface.
Is kernel driver attached to interface: False
Attaching kernel driver from interface
Is kernel driver attached to interface: True
```

2023-04-11 03:52 UTC, mcuee commented
@JoeGilkey 

Just wondering if you check out the review comments by sdijoseph to see if you can adopt the comments and update the PR. Thanks.

2023-04-21 12:58 UTC, mcuee commented
@sdijoseph 

I think your commit https://github.com/sdijoseph/LibUsbDotNet/commit/b074e9d6b6842ac07f27f7cb5855546b6bca90af is good to have to make this PR better.

Is it okay that I merge this PR and then you create a new PR to add your improvements? Thanks.

2023-04-21 13:06 UTC, sdijoseph commented
> @sdijoseph 
> 
> I think your commit https://github.com/sdijoseph/LibUsbDotNet/commit/b074e9d6b6842ac07f27f7cb5855546b6bca90af is good to have to make this PR better.
> 
> Is it okay that I merge this PR and then you create a new PR to add your improvements? Thanks.

Sure, go ahead.

2023-04-21 13:19 UTC, merged